export const properties = [
  {
    id: 1,
    title: "Luxury Villa in Palm Jumeirah",
    price: "AED 8,500,000",
    location: "Palm Jumeirah, India ",
    beds: 5,
    baths: 4,
    area: 4200,
    type: "villa",
    status: "ready",
    image: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    featured: true,
  },
  {
    id: 2,
    title: "Modern Apartment in Downtown",
    price: "AED 3,200,000",
    location: "Downtown India ",
    beds: 2,
    baths: 2,
    area: 1450,
    type: "apartment",
    status: "ready",
    image: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: 3,
    title: "Waterfront Townhouse",
    price: "AED 5,750,000",
    location: "India Marina",
    beds: 3,
    baths: 3,
    area: 2800,
    type: "townhouse",
    status: "off-plan",
    image: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
    featured: true,
  },
  {
    id: 4,
    title: "Executive Penthouse",
    price: "AED 12,000,000",
    location: "Business Bay",
    beds: 4,
    baths: 4,
    area: 3800,
    type: "penthouse",
    status: "ready",
    image: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: 5,
    title: "Garden Villa",
    price: "AED 6,900,000",
    location: "Arabian Ranches",
    beds: 4,
    baths: 3,
    area: 3200,
    type: "villa",
    status: "ready",
    image: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: 6,
    title: "Studio Apartment",
    price: "AED 1,200,000",
    location: "Jumeirah Village Circle",
    beds: 1,
    baths: 1,
    area: 800,
    type: "apartment",
    status: "off-plan",
    image: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
];

export const solutions = [
  {
    title: "Connect with a Specialist",
    description:
      "Access our dedicated team of over 400+ expert agents ready to assist you.",
    icon: "src/assets/icons/specialist.svg",
  },
  {
    title: "List Your Property",
    description:
      "Achieve optimal value by listing your property with our expert marketing strategies.",
    icon: "src/assets/icons/listProperties.svg",
  },
  {
    title: "Download Report",
    description:
      "Download the latest Comprehensive India Real Estate Market Report Q1 2025",
    icon: "src/assets/icons/downloadReport.svg",
  },
  {
    title: "Explore India Projects",
    description:
      "Browse and find your ideal property from our extensive portfolio of India projects.",
    icon: "src/assets/icons/skyscraper.svg",
  },
];

export const testimonials = [
  {
    name: "M. Zakariya",
    time: "1 year ago",
    title: "Found the Perfect Investment Property!",
    content:
      "Even though I’m an experienced investor, trying to invest in India property for the first time was overwhelming. I was lost in a sea of options and di...",
    stars: 5,
    gender: "male",
  },
  {
    name: "K. Ashwin",
    time: "1 year ago",
    title: "I'm Living in a Perfect Family Home!",
    content:
      "Moving to India with my wife and two kids was a huge change, and finding a home for my family was my top priority but also a big headache. Provident R...",
    stars: 5,
    gender: "male",
  },
  {
    name: "M. Poulin",
    time: "1 year ago",
    title: "Smart Investment Advice for a First-Time Buyer",
    content:
      "As a first-time property buyer, I was pretty confused and didn’t know where to start. Provident Real Estate’s agents were incredibly knowledgeable and...",
    stars: 5,
    gender: "female",
  },
  {
    name: "M. Zakariya",
    time: "1 year ago",
    title: "Found the Perfect Investment Property!",
    content:
      "Even though I’m an experienced investor, trying to invest in India property for the first time was overwhelming. I was lost in a sea of options and di...",
    stars: 5,
    gender: "male",
  },
  {
    name: "K. Ashwin",
    time: "1 year ago",
    title: "I'm Living in a Perfect Family Home!",
    content:
      "Moving to India with my wife and two kids was a huge change, and finding a home for my family was my top priority but also a big headache. Provident R...",
    stars: 5,
    gender: "male",
  },
  {
    name: "M. Poulin",
    time: "1 year ago",
    title: "Smart Investment Advice for a First-Time Buyer",
    content:
      "As a first-time property buyer, I was pretty confused and didn’t know where to start. Provident Real Estate’s agents were incredibly knowledgeable and...",
    stars: 5,
    gender: "female",
  },
];

export const propertyData = [
  {
    title: "Crestlane",
    developer: "Meraas",
    price: "AED 2.62M",
    location: "City Walk",
    beds: ["1", "2", "3", "4", "5"],
    tags: ["Apartment", "Ponthouse", "Duelux"],
    year: "2024",
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    title: "Bayfront Marina Residences",
    developer: "Sobha Realty",
    price: "AED 1.33M",
    location: "Sobha Siniya Island",
    beds: ["1", "2", "3"],
    tags: ["Apartment"],
    year: "2023",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    title: "Binghamton Circle",
    developer: "Binghamton",
    price: "AED 675K",
    location: "Jumeirah Village Circle (JVC)",
    beds: ["1", "2", "3"],
    tags: ["Apartment", "Studio", "Offices"],
    year: "2025",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    title: "Crestlane",
    developer: "Meraas",
    price: "AED 2.62M",
    location: "City Walk",
    beds: ["1", "2", "3", "4", "5"],
    tags: ["Apartment", "Ponthouse", "Duelux"],
    year: "2024",
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    title: "Bayfront Marina Residences",
    developer: "Sobha Realty",
    price: "AED 1.33M",
    location: "Sobha Siniya Island",
    beds: ["1", "2", "3"],
    tags: ["Apartment"],
    year: "2023",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    title: "Binghamton Circle",
    developer: "Binghamton",
    price: "AED 675K",
    location: "Jumeirah Village Circle (JVC)",
    beds: ["1", "2", "3"],
    tags: ["Apartment", "Studio", "Offices"],
    year: "2025",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    ],
  },
];

export const consultants = [
  {
    name: "Mariz Nessim",
    role: "Consultant - Primary Sales",
    languages: ["English", "Arabic"],
    image: "/images/mariz.jpg",
    emailLink: "mailto:mariz.nessim@example.com",
    callLink: "tel:+971501234567",
    whatsappLink: "https://wa.me/971501234567",
  },
  {
    name: "Ahmed Saleh",
    role: "Senior Property Advisor",
    languages: ["English", "French"],
    image: "/images/ahmed.jpg",
    emailLink: "mailto:ahmed.saleh@example.com",
    callLink: "tel:+971509876543",
    whatsappLink: "https://wa.me/971509876543",
  },
  {
    name: "Fatima Al Ali",
    role: "Leasing Consultant",
    languages: ["Arabic", "English"],
    image: "/images/fatima.jpg",
    emailLink: "mailto:fatima.alali@example.com",
    callLink: "tel:+971502345678",
    whatsappLink: "https://wa.me/971502345678",
  },
  {
    name: "John Peterson",
    role: "Off-Plan Sales Specialist",
    languages: ["English", "Russian"],
    image: "/images/john.jpg",
    emailLink: "mailto:john.peterson@example.com",
    callLink: "tel:+971504567890",
    whatsappLink: "https://wa.me/971504567890",
  },
  {
    name: "Lina Rashed",
    role: "Real Estate Strategist",
    languages: ["English", "Urdu"],
    image: "/images/lina.jpg",
    emailLink: "mailto:lina.rashed@example.com",
    callLink: "tel:+971506543210",
    whatsappLink: "https://wa.me/971506543210",
  },
  {
    name: "Omar Youssef",
    role: "Luxury Property Consultant",
    languages: ["Arabic", "English", "French"],
    image: "/images/omar.jpg",
    emailLink: "mailto:omar.youssef@example.com",
    callLink: "tel:+971505678432",
    whatsappLink: "https://wa.me/971505678432",
  },
];

export const developers = [
  {
    id: 7,
    name: "Emaar",
    logo: "https://providentestate.com/storage/images/logos/emaar-logo.png",
    link: "/developers/emaar",
    desc: "Luxury real estate developer shaping India's skyline with premium properties. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 8,
    name: "Damac",
    logo: "https://providentestate.com/storage/images/logos/damac-logo.png",
    link: "/developers/damac",
    desc: "Luxury real estate developer shaping India's skyline with premium properties. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 9,
    name: "Nakheel",
    logo: "https://providentestate.com/storage/images/logos/nakheel-logo.png",
    link: "/developers/nakheel",
    desc: "Luxury real estate developer shaping India's skyline with premium properties. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },

  {
    id: 1,
    name: "Emaar",
    logo: "https://img.freepik.com/free-photo/3d-business-man-sitting-table-office-with-laptop_107791-16770.jpg?w=740&t=st=1710696700~exp=1710700300~hmac=8ad2b5e3eabc8022a63f9b0a6786db52ff94d9539cfab2789f95e12d9263d86e",
    link: "/developers/emaar",
    desc: "Leading developer of iconic projects including Burj Khalifa and Downtown India. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 2,
    name: "Damac",
    logo: "https://img.freepik.com/free-photo/businessman-working-desk_23-2148170204.jpg?w=740",
    link: "/developers/damac",
    desc: "Luxury real estate developer shaping India's skyline with premium properties. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 3,
    name: "Nakheel",
    logo: "https://img.freepik.com/free-photo/manager-meeting-office_23-2149300964.jpg?w=740",
    link: "/developers/nakheel",
    desc: "Master developer of the world-famous Palm Jumeirah and Deira Islands. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 4,
    name: "Sobha",
    logo: "https://img.freepik.com/free-photo/marketing-manager-presenting-company-results-team_23-2148887087.jpg?w=740",
    link: "/developers/sobha",
    desc: "Premium developer known for quality and integrated communities like Sobha Hartland. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 5,
    name: "Ellington",
    logo: "https://img.freepik.com/free-photo/creative-office-business-team_23-2148892002.jpg?w=740",
    link: "/developers/ellington",
    desc: "Boutique developer focused on design-led luxury lifestyle residences. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 6,
    name: "Meraas",
    logo: "https://img.freepik.com/free-photo/coworkers-meeting-office_23-2149300961.jpg?w=740",
    link: "/developers/meraas",
    desc: "Creator of urban living destinations like City Walk, La Mer and Bluewaters Island. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
];

export const filterdata = [
  {
    label: "Location",
    options: [
      "All Locations",
      "Downtown India ",
      "India Marina",
      "Palm Jumeirah",
      "Business Bay",
      "Jumeirah Village Circle",
    ],
  },
  {
    label: "Property Type",
    options: ["All Types", "Apartment", "Villa", "Townhouse", "Penthouse"],
  },
  {
    label: "Price Range",
    options: [
      "Any Price",
      "AED 0 - 1,000,000",
      "AED 1,000,000 - 3,000,000",
      "AED 3,000,000 - 5,000,000",
      "AED 5,000,000",
    ],
  },
];

export const deve = [
  {
    id: 1,
    name: "Lodha Group",
    logo: "https://upload.wikimedia.org/wikipedia/en/6/6e/Lodha_Group_logo.png",
    link: "/developers/lodha",
    desc: "One of India’s top real estate players with luxurious skyscrapers across Mumbai, Pune, and beyond.",
  },
  {
    id: 2,
    name: "Godrej Properties",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/49/Godrej_Properties_Logo.svg",
    link: "/developers/godrej",
    desc: "A legacy brand combining innovation and sustainability in residential and commercial properties across India.",
  },
  {
    id: 3,
    name: "Prestige Group",
    logo: "https://prestigeconstructions.com/images/logo.png",
    link: "/developers/prestige",
    desc: "Renowned in South India, delivering premium projects across Bengaluru, Chennai, and Hyderabad.",
  },
  {
    id: 4,
    name: "Brigade Group",
    logo: "https://www.brigadegroup.com/sites/default/files/logo_2.png",
    link: "/developers/brigade",
    desc: "Pioneers of integrated enclaves, office spaces, malls, and hotels primarily in South India.",
  },
  {
    id: 5,
    name: "Sobha Limited",
    logo: "https://www.sobha.com/wp-content/uploads/2021/06/SOBHA_LOGO.jpg",
    link: "/developers/sobha",
    desc: "Synonymous with luxury, Sobha delivers meticulous craftsmanship and global quality standards.",
  },
  {
    id: 6,
    name: "DLF",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/e3/DLF_Limited_Logo.svg",
    link: "/developers/dlf",
    desc: "India’s largest publicly listed real estate company shaping Gurugram and Delhi NCR skyline.",
  },
  {
    id: 7,
    name: "Emaar",
    logo: "https://providentestate.com/storage/images/logos/emaar-logo.png",
    link: "/developers/emaar",
    desc: "Luxury real estate developer shaping India's skyline with premium properties. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 8,
    name: "Tata Housing",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/74/Tata_Housing_Logo.png",
    link: "/developers/tata-housing",
    desc: "A Tata enterprise bringing affordable to luxury housing with trust and innovation at its core.",
  },
  {
    id: 9,
    name: "Oberoi Realty",
    logo: "https://www.oberoirealty.com/images/logo.png",
    link: "/developers/oberoi",
    desc: "High-end real estate across Mumbai with a focus on elegance, design, and lifestyle amenities.",
  },
  {
    id: 10,
    name: "Runwal Group",
    logo: "https://www.runwal.com/assets/images/logo.png",
    link: "/developers/runwal",
    desc: "Premium township and residential developers with a strong footprint across Mumbai suburbs.",
  },
  {
    id: 11,
    name: "Mahindra Lifespaces",
    logo: "https://www.mahindralifespaces.com/themes/custom/mahindra/logo.svg",
    link: "/developers/mahindra",
    desc: "Eco-conscious homes and integrated cities blending modern living with sustainability.",
  },
  {
    id: 12,
    name: "Piramal Realty",
    logo: "https://www.piramalrealty.com/assets/img/logo.png",
    link: "/developers/piramal",
    desc: "Backed by the Piramal Group, they focus on luxurious residences in Mumbai.",
  },
  {
    id: 13,
    name: "Hiranandani",
    logo: "https://www.hiranandani.com/assets/images/logo.png",
    link: "/developers/hiranandani",
    desc: "Creators of iconic townships like Hiranandani Powai & Thane; redefining suburban lifestyle.",
  },
  {
    id: 14,
    name: "Shapoorji Pallonji",
    logo: "https://www.shapoorjirealestate.com/assets/images/logo.png",
    link: "/developers/shapoorji",
    desc: "Historic infrastructure and real estate giant with pan-India premium developments.",
  },
  {
    id: 15,
    name: "ATS Greens",
    logo: "https://www.atsgreens.com/images/logo.png",
    link: "/developers/ats",
    desc: "Well-known builder in NCR offering high-quality residential projects with amenities galore.",
  },
  {
    id: 16,
    name: "Salarpuria Sattva",
    logo: "https://www.sattvagroup.in/images/logo.svg",
    link: "/developers/sattva",
    desc: "Blending innovation and quality in commercial and residential developments across South India.",
  },
  {
    id: 17,
    name: "TVS Emerald",
    logo: "https://www.tvsemerald.com/images/logo.png",
    link: "/developers/tvs",
    desc: "Part of the TVS Group, focused on delivering smart, affordable homes in Chennai and Bengaluru.",
  },
  {
    id: 18,
    name: "Puravankara",
    logo: "https://www.puravankara.com/assets/images/logo.svg",
    link: "/developers/puravankara",
    desc: "Offering a range of residential properties from affordable Provident housing to luxury homes.",
  },
  {
    id: 19,
    name: "Kolte-Patil",
    logo: "https://www.koltepatil.com/assets/images/logo.png",
    link: "/developers/kolte-patil",
    desc: "Prominent in Pune, Kolte Patil has delivered award-winning designs and lifestyle apartments.",
  },
  {
    id: 20,
    name: "Ajmera Realty",
    logo: "https://ajmera.com/images/logo.png",
    link: "/developers/ajmera",
    desc: "From Mumbai to Bengaluru, Ajmera delivers quality living with affordability and style.",
  },
];

export const area = [
  {
    id: 1,
    name: "Lodha Group",
    logo: "https://upload.wikimedia.org/wikipedia/en/6/6e/Lodha_Group_logo.png",
    link: "/developers/lodha",
    desc: "One of India’s top real estate players with luxurious skyscrapers across Mumbai, Pune, and beyond.",
  },
  {
    id: 2,
    name: "Godrej Properties",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/49/Godrej_Properties_Logo.svg",
    link: "/developers/godrej",
    desc: "A legacy brand combining innovation and sustainability in residential and commercial properties across India.",
  },
  {
    id: 3,
    name: "Prestige Group",
    logo: "https://prestigeconstructions.com/images/logo.png",
    link: "/developers/prestige",
    desc: "Renowned in South India, delivering premium projects across Bengaluru, Chennai, and Hyderabad.",
  },
  {
    id: 4,
    name: "Brigade Group",
    logo: "https://www.brigadegroup.com/sites/default/files/logo_2.png",
    link: "/developers/brigade",
    desc: "Pioneers of integrated enclaves, office spaces, malls, and hotels primarily in South India.",
  },
  {
    id: 5,
    name: "Sobha Limited",
    logo: "https://www.sobha.com/wp-content/uploads/2021/06/SOBHA_LOGO.jpg",
    link: "/developers/sobha",
    desc: "Synonymous with luxury, Sobha delivers meticulous craftsmanship and global quality standards.",
  },
  {
    id: 6,
    name: "DLF",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/e3/DLF_Limited_Logo.svg",
    link: "/developers/dlf",
    desc: "India’s largest publicly listed real estate company shaping Gurugram and Delhi NCR skyline.",
  },
  {
    id: 7,
    name: "Emaar",
    logo: "https://providentestate.com/storage/images/logos/emaar-logo.png",
    link: "/developers/emaar",
    desc: "Luxury real estate developer shaping India's skyline with premium properties. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem minima doloremque unde vitae.",
  },
  {
    id: 8,
    name: "Tata Housing",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/74/Tata_Housing_Logo.png",
    link: "/developers/tata-housing",
    desc: "A Tata enterprise bringing affordable to luxury housing with trust and innovation at its core.",
  },
  {
    id: 9,
    name: "Oberoi Realty",
    logo: "https://www.oberoirealty.com/images/logo.png",
    link: "/developers/oberoi",
    desc: "High-end real estate across Mumbai with a focus on elegance, design, and lifestyle amenities.",
  },
  {
    id: 10,
    name: "Runwal Group",
    logo: "https://www.runwal.com/assets/images/logo.png",
    link: "/developers/runwal",
    desc: "Premium township and residential developers with a strong footprint across Mumbai suburbs.",
  },
  {
    id: 11,
    name: "Mahindra Lifespaces",
    logo: "https://www.mahindralifespaces.com/themes/custom/mahindra/logo.svg",
    link: "/developers/mahindra",
    desc: "Eco-conscious homes and integrated cities blending modern living with sustainability.",
  },
  {
    id: 12,
    name: "Piramal Realty",
    logo: "https://www.piramalrealty.com/assets/img/logo.png",
    link: "/developers/piramal",
    desc: "Backed by the Piramal Group, they focus on luxurious residences in Mumbai.",
  },
  {
    id: 13,
    name: "Hiranandani",
    logo: "https://www.hiranandani.com/assets/images/logo.png",
    link: "/developers/hiranandani",
    desc: "Creators of iconic townships like Hiranandani Powai & Thane; redefining suburban lifestyle.",
  },
  {
    id: 14,
    name: "Shapoorji Pallonji",
    logo: "https://www.shapoorjirealestate.com/assets/images/logo.png",
    link: "/developers/shapoorji",
    desc: "Historic infrastructure and real estate giant with pan-India premium developments.",
  },
  {
    id: 15,
    name: "ATS Greens",
    logo: "https://www.atsgreens.com/images/logo.png",
    link: "/developers/ats",
    desc: "Well-known builder in NCR offering high-quality residential projects with amenities galore.",
  },
  {
    id: 16,
    name: "Salarpuria Sattva",
    logo: "https://www.sattvagroup.in/images/logo.svg",
    link: "/developers/sattva",
    desc: "Blending innovation and quality in commercial and residential developments across South India.",
  },
  {
    id: 17,
    name: "TVS Emerald",
    logo: "https://www.tvsemerald.com/images/logo.png",
    link: "/developers/tvs",
    desc: "Part of the TVS Group, focused on delivering smart, affordable homes in Chennai and Bengaluru.",
  },
  {
    id: 18,
    name: "Puravankara",
    logo: "https://www.puravankara.com/assets/images/logo.svg",
    link: "/developers/puravankara",
    desc: "Offering a range of residential properties from affordable Provident housing to luxury homes.",
  },
  {
    id: 19,
    name: "Kolte-Patil",
    logo: "https://www.koltepatil.com/assets/images/logo.png",
    link: "/developers/kolte-patil",
    desc: "Prominent in Pune, Kolte Patil has delivered award-winning designs and lifestyle apartments.",
  },
  {
    id: 20,
    name: "Ajmera Realty",
    logo: "https://ajmera.com/images/logo.png",
    link: "/developers/ajmera",
    desc: "From Mumbai to Bengaluru, Ajmera delivers quality living with affordability and style.",
  },
];

